// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPklW1klj32n2Sx_cD12CmpzD9OxSMg0',
    appId: '1:1005856368235:android:70eb297f9b13da22dd332e',
    messagingSenderId: '1005856368235',
    projectId: 'najm-suhail-project',
    storageBucket: 'najm-suhail-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOZijseaUJhAuMzxir3zmfGP0yx3XeZQ',
    appId: '1:1005856368235:ios:4ff960ecfa0796dcdd332e',
    messagingSenderId: '1005856368235',
    projectId: 'najm-suhail-project',
    storageBucket: 'najm-suhail-project.appspot.com',
    androidClientId: '1005856368235-5bi25jg4ufh2r6fp4rvvg1u4bnqjpbcg.apps.googleusercontent.com',
    iosClientId: '1005856368235-nkfb0uiqlj300fkkr1c1hvvmr5g3i3tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.najmSuhail',
  );
}
